INSERT INTO directory_finished (bucket, directory_name, directory_finished) 
    VALUES (1, '2017-10-01T06:00Z Wind-U', false);
INSERT INTO directory_finished (bucket, directory_name, directory_finished) 
    VALUES (1, '2017-10-01T09:00Z Wind-U', false);
INSERT INTO directory_finished (bucket, directory_name, directory_finished) 
    VALUES (1, '2017-10-01T12:00Z Wind-U', false);
INSERT INTO directory_finished (bucket, directory_name, directory_finished) 
    VALUES (1, '2017-10-01T06:00Z Flux', true);
INSERT INTO directory_finished (bucket, directory_name, directory_finished) 
    VALUES (1, '2017-10-01T09:00Z Flux', true);
INSERT INTO directory_finished (bucket, directory_name, directory_finished) 
    VALUES (1, '2017-10-01T12:00Z Flux', false);
    